name: Publish

# Controls when the action will run. 
on:
  # Triggers the workflow on new SemVer tags
  push:
    branches:
      - master
    tags: 
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v3.4.1
        name: generate tags
        id: meta
        with:
          images: ghcr.io/siafoundation/siad
          tags: |
            type=ref,event=branch
            type=sha,prefix=
            type=semver,pattern={{version}}
      - uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ darwin, linux, windows ]
        arch: [ arm64, amd64 ]
        exclude:
          - os: windows
            arch: arm64
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^v1.17
      - name: build ${{ matrix.os }}/${{ matrix.arch }}
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: make static
      - uses: actions/upload-artifact@v2
        with:
          name: sia-${{ matrix.os }}-${{ matrix.arch }}
          path: release/*
          retention-days: 30
